@WebApplication1_HostAddress = http://localhost:5290

Post {{WebApplication1_HostAddress}}/weatherforecast/profile3
Content-Type: application/json

{
  "Age":40,
  "IsSubscribed": true,
  "Courses": ["SQL", 123, null],
  "Pet": {
    "Type":123
  }
}
