@WebApplication1_HostAddress = http://localhost:5290

Post {{WebApplication1_HostAddress}}/weatherforecast/profile2
Content-Type: application/json

{
  "Name": "mattias",
  "Age":40,
  "IsSubscribed": true,
  "Courses": ["SQL", "C#"],
  "Pet": {
    "Name":"Fido",
    "Type":"Snake"
  }
}
